[package]
name = "scrambler"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
iced = "0.9"
serde = "1.0"
serde_json = "1.0"
log = "0.4"
env_logger = "0.10"
const_format = "0.2"